alter table public.marketplace_seller_payout_accounts
  add column if not exists account_number_encrypted text,
  add column if not exists promptpay_id_encrypted text;

alter table public.marketplace_payouts
  add column if not exists account_number_snapshot_encrypted text;

alter table public.marketplace_finance_settings
  add column if not exists promptpay_id_encrypted text,
  add column if not exists payout_account_number_encrypted text;

comment on column public.marketplace_seller_payout_accounts.account_number_encrypted is
  'AES-256-GCM ciphertext generated by the application. Plaintext account_number must remain null.';

comment on column public.marketplace_seller_payout_accounts.promptpay_id_encrypted is
  'AES-256-GCM ciphertext generated by the application. Plaintext promptpay_id must remain null.';

comment on column public.marketplace_payouts.account_number_snapshot_encrypted is
  'AES-256-GCM ciphertext preserving the payout destination at transaction time.';

comment on column public.marketplace_finance_settings.promptpay_id_encrypted is
  'AES-256-GCM ciphertext for the platform receiving account.';

comment on column public.marketplace_finance_settings.payout_account_number_encrypted is
  'AES-256-GCM ciphertext for the platform payout source account.';
